version: '2'
services:
  dmptool:
    build:
      context: .
      args:
        GIT: https://github.com/der-scheme/dmptool.git
        RELEASE: build-test
        JOBS: 4
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf/etc/nginx/custom.conf:/etc/nginx/custom.conf
      - ${PWD}/conf/etc/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ${PWD}/conf/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
      - ${PWD}/conf/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ${PWD}/conf/etc/ssl/extern/:/etc/ssl/extern/
      - ${PWD}/conf/var/www/app/config/app_config.yml:/var/www/app/config/app_config.yml
      - ${PWD}/conf/var/www/app/config/layout.rb:/var/www/app/config/layout.rb
      - ${PWD}/conf/var/www/app/config/database.yml:/var/www/app/config/database.yml
      - ${PWD}/conf/var/www/app/config/shibboleth.yml:/var/www/app/config/shibboleth.yml
