version: '2'
services:
  dmptool:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/etc/nginx/custom.conf:/etc/nginx/custom.conf
      - ./conf/etc/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./conf/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
      - ./conf/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ./conf/etc/ssl/extern/:/etc/ssl/extern/
      - ./conf/var/www/app/config/app_config.rb:/var/www/app/config/app_config.rb
      - ./conf/var/www/app/config/layout.rb:/var/www/app/config/layout.rb
      - ./conf/var/www/app/config/database.yml:/var/www/app/config/database.yml
      - ./conf/var/www/app/config/shibboleth.yml:/var/www/app/config/shibboleth.yml
