version: '2'
services:
  dmptool:
    build:
      context: .
      args:
        APP_DIR: /var/www/app
        GIT: ${DMPTOOL_REPOSITORY}
        JOBS: ${CPU_CORES}
        RELEASE: ${DMPTOOL_RELEASE}
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${MYSQLD_SOCKET}:/var/run/mysqld/mysqld.sock
      - ./conf/etc/apache2/conf/custom.conf:/etc/apache2/conf/custom.conf
      - ./conf/etc/apache2/conf/name.conf:/etc/apache2/conf/name.conf
      - ./conf/etc/apache2/conf/ssl.conf:/etc/apache2/conf/ssl.conf
      - ./conf/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
      - ./conf/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ./conf/etc/ssl/extern/:/etc/ssl/extern/
      - ./conf/var/www/app/config/app_config.yml:${APP_DIR}/config/app_config.yml
      - ./conf/var/www/app/config/layout.rb:${APP_DIR}/config/layout.rb
      - ./conf/var/www/app/config/database.yml:${APP_DIR}/config/database.yml
      - ./conf/var/www/app/config/shibboleth.yml:${APP_DIR}/config/shibboleth.yml
      - ./conf/db/schema.rb:${APP_DIR}/db/schema.rb
